apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-shared-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-********::fsap-********
    volumeAttributes:
      path: "/shared_drive"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
